# Generated by Django 5.2.8 on 2026-06-10 18:14

from django.db import migrations, models


def set_initial_unit_prices(apps, schema_editor):
    OrderItem = apps.get_model("store", "OrderItem")

    order_items = OrderItem.objects.select_related("product").filter(
        unit_price__isnull=True
    )

    for item in order_items:
        item.unit_price = item.product.price
        item.save(update_fields=["unit_price"])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.RunPython(set_initial_unit_prices, migrations.RunPython.noop),
    ]
