# Generated by Django 5.2.8 on 2026-06-10 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_orderitem_orderitem_quantity_positive_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contactlead',
            index=models.Index(fields=['created_at'], name='contact_created_idx'),
        ),
        migrations.AddIndex(
            model_name='contactlead',
            index=models.Index(fields=['status', 'created_at'], name='contact_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['created_at'], name='event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['event_type', 'created_at'], name='event_type_date_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['severity', 'created_at'], name='event_severity_date_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['user', 'created_at'], name='event_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['date_ordered'], name='order_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'date_ordered'], name='order_customer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'date_ordered'], name='order_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='orderitem_order_product_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='product_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock', 'created_at'], name='product_stock_created_idx'),
        ),
    ]
