# Generated by Django 5.2.8 on 2026-06-10 21:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_contactlead_contact_created_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='contactlead',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['nuevo', 'en_proceso', 'respondido', 'cerrado'])), name='contact_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='eventlog',
            constraint=models.CheckConstraint(condition=models.Q(('severity__in', ['info', 'warning', 'error'])), name='event_severity_valid'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pendiente', 'pagado', 'en_preparacion', 'enviado', 'entregado', 'cancelado', 'reembolsado'])), name='order_status_valid'),
        ),
    ]
