# Generated by Django 5.2.8 on 2026-06-10 21:39

import django.db.models.deletion
from django.db import migrations, models


def set_initial_product_names(apps, schema_editor):
    OrderItem = apps.get_model("store", "OrderItem")

    order_items = OrderItem.objects.select_related("product").filter(
        product_name=""
    )

    for item in order_items:
        item.product_name = item.product.name
        item.save(update_fields=["product_name"])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_contactlead_contact_status_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.RunPython(set_initial_product_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product'),
        ),
    ]
