# Generated by Django 5.2.8 on 2026-06-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=160)),
                ('discount_type', models.CharField(choices=[('percent', 'Porcentaje'), ('fixed', 'Valor fijo')], default='percent', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('code',),
                'indexes': [models.Index(fields=['code', 'is_active'], name='discount_code_active_idx'), models.Index(fields=['is_active', 'starts_at', 'ends_at'], name='discount_active_dates_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('discount_type', 'fixed'), ('value__gte', 0)), models.Q(('discount_type', 'percent'), ('value__gte', 0), ('value__lte', 100)), _connector='OR'), name='discount_value_valid'), models.CheckConstraint(condition=models.Q(('min_order_total__gte', 0)), name='discount_min_total_non_negative')],
            },
        ),
    ]
