# Generated by Django 5.2.8 on 2026-06-14 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_order_coupon_code_order_discount_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('en_preparacion', 'En preparacion'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='store.order')),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['order', 'created_at'], name='order_status_order_date_idx'), models.Index(fields=['status', 'created_at'], name='order_status_state_date_idx')],
            },
        ),
    ]
