# Generated by Django 5.2.8 on 2026-06-14 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='store.customer')),
            ],
            options={
                'ordering': ('-is_default', '-updated_at', '-id'),
                'indexes': [models.Index(fields=['customer', 'is_default'], name='shipaddr_customer_default_idx'), models.Index(fields=['customer', 'updated_at'], name='shipaddr_customer_updated_idx')],
            },
        ),
    ]
