# Generated by Django 5.2.8 on 2026-06-17 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_shippingaddress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('checkout', 'Salida por compra'), ('cancel_restore', 'Entrada por cancelacion'), ('admin_adjustment', 'Ajuste administrativo')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('stock_before', models.PositiveIntegerField()),
                ('stock_after', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='store.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['product', 'created_at'], name='stockmov_product_date_idx'), models.Index(fields=['movement_type', 'created_at'], name='stockmov_type_date_idx'), models.Index(fields=['order', 'created_at'], name='stockmov_order_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__lt', 0), ('quantity__gt', 0), _connector='OR'), name='stockmovement_quantity_not_zero')],
            },
        ),
    ]
