# Generated by Django 5.2.8 on 2026-06-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'checkout_token'], name='order_customer_checkout_idx'),
        ),
    ]
