# Generated by Django 5.2.8 on 2026-06-18 01:45

import django.db.models.expressions
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_order_order_subtotal_non_negative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('movement_type__in', ['checkout', 'cancel_restore', 'admin_adjustment'])), name='stockmovement_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'checkout'), ('quantity__lt', 0)), models.Q(('movement_type', 'cancel_restore'), ('quantity__gt', 0)), ('movement_type', 'admin_adjustment'), _connector='OR'), name='stockmovement_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('stock_after', django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Cast(models.F('stock_before'), output_field=models.BigIntegerField()), '+', models.F('quantity')))), name='stockmovement_balance_valid'),
        ),
    ]
