# Generated by Django 5.2.8 on 2026-06-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_stockmovement_stockmovement_type_valid_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orderitem_order_product_idx',
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='orderitem_order_product_unique'),
        ),
    ]
