# Generated by Django 5.2.8 on 2026-06-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_remove_orderitem_orderitem_order_product_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.CheckConstraint(condition=models.Q(('max_uses__isnull', True), ('used_count__lte', models.F('max_uses')), _connector='OR'), name='discount_usage_within_limit'),
        ),
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.CheckConstraint(condition=models.Q(('starts_at__isnull', True), ('ends_at__isnull', True), ('starts_at__lte', models.F('ends_at')), _connector='OR'), name='discount_dates_valid'),
        ),
    ]
