# Generated by Django 5.2.8 on 2026-06-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_discountcode_discount_usage_within_limit_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('delivered_at__isnull', True), models.Q(('delivered_at__gte', models.F('shipped_at')), ('shipped_at__isnull', False)), _connector='OR'), name='order_tracking_dates_valid'),
        ),
    ]
