# Generated by Django 5.2.8 on 2026-06-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_order_order_tracking_dates_valid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed', True), ('status__in', ['pagado', 'en_preparacion', 'enviado', 'entregado'])), models.Q(('completed', False), ('status__in', ['pendiente', 'cancelado', 'reembolsado'])), _connector='OR'), name='order_status_completed_valid'),
        ),
    ]
