# Generated by Django 5.2.8 on 2026-06-18 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_order_order_status_completed_valid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pendiente', 'pagado', 'en_preparacion', 'enviado', 'entregado', 'cancelado', 'reembolsado'])), name='orderhistory_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='orderstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('previous_status', ''), ('previous_status__in', ['pendiente', 'pagado', 'en_preparacion', 'enviado', 'entregado', 'cancelado', 'reembolsado']), _connector='OR'), name='orderhistory_previous_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='orderstatushistory',
            constraint=models.CheckConstraint(condition=models.Q(('previous_status', ''), models.Q(('previous_status', models.F('status')), _negated=True), _connector='OR'), name='orderhistory_transition_changed'),
        ),
    ]
