# Generated by Django 5.2.15 on 2026-06-20 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_orderstatushistory_orderhistory_status_valid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(fields=('order', 'product', 'movement_type'), name='stockmov_order_prod_type_uniq'),
        ),
    ]
