# Generated by Django 5.2.15 on 2026-06-20 10:40

import django.core.validators
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_stockmovement_stockmov_order_prod_type_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=store.models.product_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp', 'avif')), store.models.validate_product_image]),
        ),
    ]
